  <a  href="Huruf_A/filter.php"><button  name="login" class="btn btn-danger btn-fill">Huruf A</button></a> 
        <a   href="Huruf_B/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf B</button></a> 
         <a  href="Huruf_C/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf C</button></a> 
        <a  href="Huruf_D/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf D</button></a>
         <a  href="Huruf_E/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf E</button></a>
        <a  href="Huruf_F/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf F</button></a>
         <a  href="Huruf_G/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf G</button></a>
        <a  href="Huruf_H/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf H</button></a>
         <a   href="Huruf_I/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf I</button></a>
        <a   href="Huruf_J/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf J</button></a>
         <a  href="Huruf_K/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf K</button></a>
        <a  href="Huruf_L/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf L</button></a>
         <a   href="Huruf_M/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf M</button></a>
        <a   href="Huruf_N/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf N</button></a>
         <a   href="Huruf_O/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf O</button></a>
        <a   href="Huruf_P/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf P</button></a>
         <a   href="Huruf_R/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf R</button></a>
        <a   href="Huruf_S/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf S</button></a>
         <a  href="Huruf_T/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf T</button></a>
        <a   href="Huruf_U/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf U</button></a>
         <a   href="Huruf_V/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf V</button></a>
        <a   href="Huruf_W/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf W</button></a>
         <a  href="Huruf_Y/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf Y</button></a>
        <a  href="Huruf_Z/filter.php"><button name="login" class="btn btn-danger btn-fill">Huruf Z</button></a>